dist: trusty
sudo: required
language: bash
before_install:
- curl https://raw.githubusercontent.com/express42/otus-homeworks/2018-02/run.sh |
  bash
notifications:
  slack:
    secure: KjuhqLGA+y8jbzoaq7l6j8gUuY4TdJVKPyq1bnZ5Jgfss6nC1sYCegXvTvUgiqJ8e7oDPhTMsV5cv19I2TgqzOOS5Crq/lbfRstHrxIhg2CGZTyA2kR5G5Zdsl03Cwx4XSlRF//EdhLQ5lOs3j+yTHQn0zPvpYEcyBhlokp1twLWkgKpdZHPUKWz1Zv8KH40h1FpHH97VYczdEQHwlbEYGDWoWtDt1XlSoTxi+kAjLmSq+Z+6c3mW1UlxvnQI8y8Qj2VJpDVx+Dy60fS4IEBNYhXHAt/hLQdsw1ZvR1NmE/lU4m3tXnFzY4YLOHhP4O65HuA14GcMRcCttCzFdjIfZbGpNq4fn3wvIl7XNRS9jxwZ72E1thB3PqIAOG3bog2IuVkQqHewqqOlMpsgJ3YWhNPd9KDThhdYeib2V3r8YP5dho5f/vXOqIBduGBC8VdwtHFMJiYdH8z8nOtFea7zevp/0nynPhsvnRWbXptU3Xm60ERsSonUGylwN/xuX0cqr6y3O+gsXGDhy2AC0/1RLaruJzgVnEq5gvUz+Rkc7UI4zYuKjY7LZgq3SI4rgcrDFqyeaycp8w48A0kiOE5XlFRD24Vxi0TPostcMFq1Fv6kqJbkIU5ZcnDXepjgTDVjRlB4NTttKujM2DUgnk1MrbKuOCCig900JoVBSDqDHQ=
